export const MEDICAL_DISCLAIMER = `
This information is generated by an AI system for educational purposes only.
It is not a medical diagnosis, treatment, or a substitute for professional
medical advice. Always consult a qualified healthcare provider for any
medical concerns.
`;
